version: 1
formatters:
  helloformat:
    format: 'HELLO %(asctime)s - %(name)s - %(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: ./log/errors.log
loggers:
  console:
    level: DEBUG
    handlers: [console]
    propagate: no
  file:
    level: ERROR
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]